--[[
##############################################################################
_____/\\\\\\\\\\\____/\\\________/\\\__/\\\________/\\\__/\\\\\\\\\\\_       #
 ___/\\\/////////\\\_\/\\\_______\/\\\_\/\\\_______\/\\\_\/////\\\///__      #
  __\//\\\______\///__\//\\\______/\\\__\/\\\_______\/\\\_____\/\\\_____     #
   ___\////\\\__________\//\\\____/\\\___\/\\\_______\/\\\_____\/\\\_____    #
    ______\////\\\________\//\\\__/\\\____\/\\\_______\/\\\_____\/\\\_____   #
     _________\////\\\______\//\\\/\\\_____\/\\\_______\/\\\_____\/\\\_____  #
      __/\\\______\//\\\______\//\\\\\______\//\\\______/\\\______\/\\\_____ #
       _\///\\\\\\\\\\\/________\//\\\________\///\\\\\\\\\/____/\\\\\\\\\\\_#
        ___\///////////___________\///___________\/////////_____\///////////_#
##############################################################################
S U P E R - V I L L A I N - U I   By: Munglunch                              #
##############################################################################
--]]
local SuperVillain, L, P, C = unpack(select(2, ...));
--[[ 
########################################################## 
DB PROFILE VARS
##########################################################
]]--
C['SVBar'] = {
	['font'] = 'SVUI Number Font',
	['fontSize'] = 10,
	['cooldownSize'] = 18,
	['fontOutline'] = 'OUTLINE',
	['rightClickSelf'] = false,
	["macrotext"] = false,
	["hotkeytext"] = true,
	["hotkeyAbbrev"] = true,
	['showGrid'] = true,
	['unc'] = {r = 0.8, g = 0.1, b = 0.1, a = 0.7},
	['unpc'] = {r = 0.5, g = 0.5, b = 1, a = 0.7},
	['keyDown'] = false,
	['unlock'] = 'SHIFT',
	['Micro'] = {
		['enable'] = true,
		['mouseover'] = true,
		['alpha'] = 1,
		["buttonsize"] = 30,
		["buttonspacing"] = 4,
		["yOffset"] = 4
	},
	['Bar1'] = {
		['enable'] = true,
		['buttons'] = 12,
		['mouseover'] = false,
		['buttonsPerRow'] = 12,
		['point'] = 'BOTTOMLEFT',
		['backdrop'] = false,
		['heightMult'] = 1,
		['widthMult'] = 1,
		["buttonsize"] = 32,
		["buttonspacing"] = 2,
		["useCustomStates"] = true,
		["customStates"] = {
		    ["HUNTER"]  	= "",
		    ["WARLOCK"] 	= "[form:2] 10;",
		    ["PRIEST"]  	= "[bonusbar:1] 7;",
		    ["PALADIN"] 	= "",
		    ["MAGE"]    	= "",
		    ["ROGUE"]   	= "[stance:1] 7; [stance:2] 7; [stance:3] 7; [bonusbar:1] 7; [form:3] 7;",
		    ["DRUID"]   	= "[bonusbar:1,nostealth] 7; [bonusbar:1,stealth] 8; [bonusbar:2] 8; [bonusbar:3] 9; [bonusbar:4] 10;",
		    ["SHAMAN"]  	= "",
		    ["WARRIOR"] 	= "",
		    ["DEATHKNIGHT"] = "",
		    ["MONK"]    	= "[bonusbar:1] 7; [bonusbar:2] 8; [bonusbar:3] 9;",
		},
		['alpha'] = 1
	},
	['Bar2'] = {
		['enable'] = false,
		['mouseover'] = false,
		['buttons'] = 12,
		['buttonsPerRow'] = 12,
		['point'] = 'BOTTOMLEFT',
		['backdrop'] = false,
		['heightMult'] = 1,
		['widthMult'] = 1,
		["buttonsize"] = 32,
		["buttonspacing"] = 2,
		["useCustomStates"] = false,
		["customStates"] = {
		    ["HUNTER"]  	= "",
		    ["WARLOCK"] 	= "",
		    ["PRIEST"]  	= "",
		    ["PALADIN"] 	= "",
		    ["MAGE"]    	= "",
		    ["ROGUE"]   	= "",
		    ["DRUID"]   	= "",
		    ["SHAMAN"]  	= "",
		    ["WARRIOR"] 	= "",
		    ["DEATHKNIGHT"] = "",
		    ["MONK"]    	= "",
		},
		['alpha'] = 1
	},
	['Bar3'] = {
		['enable'] = true,
		['mouseover'] = false,
		['buttons'] = 6,
		['buttonsPerRow'] = 6,
		['point'] = 'BOTTOMLEFT',
		['backdrop'] = false,
		['heightMult'] = 1,
		['widthMult'] = 1,
		["buttonsize"] = 32,
		["buttonspacing"] = 2,
		["useCustomStates"] = false,
		["customStates"] = {
		    ["HUNTER"]  	= "",
		    ["WARLOCK"] 	= "",
		    ["PRIEST"]  	= "",
		    ["PALADIN"] 	= "",
		    ["MAGE"]    	= "",
		    ["ROGUE"]   	= "",
		    ["DRUID"]   	= "",
		    ["SHAMAN"]  	= "",
		    ["WARRIOR"] 	= "",
		    ["DEATHKNIGHT"] = "",
		    ["MONK"]    	= "",
		},
		['alpha'] = 1
	},
	['Bar4'] = {
		['enable'] = true,
		['mouseover'] = true,
		['buttons'] = 12,
		['buttonsPerRow'] = 1,
		['point'] = 'TOPRIGHT',
		['backdrop'] = false,
		['heightMult'] = 1,
		['widthMult'] = 1,
		["buttonsize"] = 32,
		["buttonspacing"] = 2,
		["useCustomStates"] = false,
		["customStates"] = {
		    ["HUNTER"]  	= "",
		    ["WARLOCK"] 	= "",
		    ["PRIEST"]  	= "",
		    ["PALADIN"] 	= "",
		    ["MAGE"]    	= "",
		    ["ROGUE"]   	= "",
		    ["DRUID"]   	= "",
		    ["SHAMAN"]  	= "",
		    ["WARRIOR"] 	= "",
		    ["DEATHKNIGHT"] = "",
		    ["MONK"]    	= "",
		},
		['alpha'] = 1
	},
	['Bar5'] = {
		['enable'] = true,
		['mouseover'] = false,
		['buttons'] = 6,
		['buttonsPerRow'] = 6,
		['point'] = 'BOTTOMLEFT',
		['backdrop'] = false,
		['heightMult'] = 1,
		['widthMult'] = 1,
		["buttonsize"] = 32,
		["buttonspacing"] = 2,
		["useCustomStates"] = false,
		["customStates"] = {
		    ["HUNTER"]  	= "",
		    ["WARLOCK"] 	= "",
		    ["PRIEST"]  	= "",
		    ["PALADIN"] 	= "",
		    ["MAGE"]    	= "",
		    ["ROGUE"]   	= "",
		    ["DRUID"]   	= "",
		    ["SHAMAN"]  	= "",
		    ["WARRIOR"] 	= "",
		    ["DEATHKNIGHT"] = "",
		    ["MONK"]    	= "",
		},
		['alpha'] = 1
	},
	['Bar6'] = {
		['enable'] = false,
		['mouseover'] = false,
		['buttons'] = 12,
		['buttonsPerRow'] = 12,
		['point'] = 'BOTTOMLEFT',
		['backdrop'] = false,
		['heightMult'] = 1,
		['widthMult'] = 1,
		["buttonsize"] = 32,
		["buttonspacing"] = 2,
		["useCustomStates"] = false,
		["customStates"] = {
		    ["HUNTER"]  	= "",
		    ["WARLOCK"] 	= "",
		    ["PRIEST"]  	= "",
		    ["PALADIN"] 	= "",
		    ["MAGE"]    	= "",
		    ["ROGUE"]   	= "",
		    ["DRUID"]   	= "",
		    ["SHAMAN"]  	= "",
		    ["WARRIOR"] 	= "",
		    ["DEATHKNIGHT"] = "",
		    ["MONK"]    	= "",
		},
		['alpha'] = 1
	},
	['Pet'] = {
		['enable'] = true,
		['mouseover'] = false,
		['buttons'] = NUM_PET_ACTION_SLOTS,
		['buttonsPerRow'] = 12,
		['point'] = 'TOPLEFT',
		['backdrop'] = false,
		['heightMult'] = 1,
		['widthMult'] = 1,
		["buttonsize"] = 24,
		["buttonspacing"] = 3,
		['alpha'] = 1
	},
	['Stance'] = {
		['enable'] = true,
		['style'] = 'darkenInactive',
		['mouseover'] = false,
		['buttons'] = NUM_STANCE_SLOTS,
		['buttonsPerRow'] = NUM_STANCE_SLOTS,
		['point'] = 'BOTTOMRIGHT',
		['backdrop'] = false,
		['heightMult'] = 1,
		['widthMult'] = 1,
		["buttonsize"] = 24,
		["buttonspacing"] = 5,
		['alpha'] = 1
	},
};
--[[ 
########################################################## 
DB PROTECTED VARS
##########################################################
]]--
P['SVBar'] = {
	['enable'] = true,
	['defaultStates'] = {
		['Bar1'] = {
		    ["HUNTER"]  	= "",
		    ["WARLOCK"] 	= "[form:2] 10;",
		    ["PRIEST"]  	= "[bonusbar:1] 7;",
		    ["PALADIN"] 	= "",
		    ["MAGE"]    	= "",
		    ["ROGUE"]   	= "[stance:1] 7; [stance:2] 7; [stance:3] 7; [bonusbar:1] 7; [form:3] 7;",
		    ["DRUID"]   	= "[bonusbar:1,nostealth] 7; [bonusbar:1,stealth] 8; [bonusbar:2] 8; [bonusbar:3] 9; [bonusbar:4] 10;",
		    ["SHAMAN"]  	= "",
		    ["WARRIOR"] 	= "",
		    ["DEATHKNIGHT"] = "",
		    ["MONK"]    	= "[bonusbar:1] 7; [bonusbar:2] 8; [bonusbar:3] 9;",
		},
		['Bar2'] = {
		    ["HUNTER"]  	= "",
		    ["WARLOCK"] 	= "",
		    ["PRIEST"]  	= "",
		    ["PALADIN"] 	= "",
		    ["MAGE"]    	= "",
		    ["ROGUE"]   	= "",
		    ["DRUID"]   	= "",
		    ["SHAMAN"]  	= "",
		    ["WARRIOR"] 	= "",
		    ["DEATHKNIGHT"] = "",
		    ["MONK"]    	= "",
		},
		['Bar3'] = {
		    ["HUNTER"]  	= "",
		    ["WARLOCK"] 	= "",
		    ["PRIEST"]  	= "",
		    ["PALADIN"] 	= "",
		    ["MAGE"]    	= "",
		    ["ROGUE"]   	= "",
		    ["DRUID"]   	= "",
		    ["SHAMAN"]  	= "",
		    ["WARRIOR"] 	= "",
		    ["DEATHKNIGHT"] = "",
		    ["MONK"]    	= "",
		},
		['Bar4'] = {
		    ["HUNTER"]  	= "",
		    ["WARLOCK"] 	= "",
		    ["PRIEST"]  	= "",
		    ["PALADIN"] 	= "",
		    ["MAGE"]    	= "",
		    ["ROGUE"]   	= "",
		    ["DRUID"]   	= "",
		    ["SHAMAN"]  	= "",
		    ["WARRIOR"] 	= "",
		    ["DEATHKNIGHT"] = "",
		    ["MONK"]    	= "",
		},
		['Bar5'] = {
		    ["HUNTER"]  	= "",
		    ["WARLOCK"] 	= "",
		    ["PRIEST"]  	= "",
		    ["PALADIN"] 	= "",
		    ["MAGE"]    	= "",
		    ["ROGUE"]   	= "",
		    ["DRUID"]   	= "",
		    ["SHAMAN"]  	= "",
		    ["WARRIOR"] 	= "",
		    ["DEATHKNIGHT"] = "",
		    ["MONK"]    	= "",
		},
		['Bar6'] = {
		    ["HUNTER"]  	= "",
		    ["WARLOCK"] 	= "",
		    ["PRIEST"]  	= "",
		    ["PALADIN"] 	= "",
		    ["MAGE"]    	= "",
		    ["ROGUE"]   	= "",
		    ["DRUID"]   	= "",
		    ["SHAMAN"]  	= "",
		    ["WARRIOR"] 	= "",
		    ["DEATHKNIGHT"] = "",
		    ["MONK"]    	= "",
		},
	}
};